### ISSUE TITLE
Interface mappings can be incorrect when 'peer_interface' isn't specified everywhere

### ISSUE THREAD

**Issue by andrewbonney** [arista-netdevops-community/eos_designs_to_containerlab#14]
In our deployment we have `containerlab_custom_interface_mapping` set to True, but we don't define `peer_interface` for every interface, for example where these link to hosts rather than switches. As a result of this, whilst our switch config represents the full set of interfaces, the containerlab topology only includes a small number of them. At present, this results in high numbered interfaces like Ethernet31/1 mapping to low numbered containerlab interfaces like Ethernet1/1, meaning the config applied to the switch doesn't match up with the topology. This is an example mappings file:

```
{
    "EthernetIntf": {
        "eth1": "Ethernet31/1",
        "eth2": "Ethernet32/1"
    },
    "ManagementIntf": {
        "eth0": "Management1"
    }
}
```

I've tested a fix for this which involves moving the code block in https://github.com/arista-netdevops-community/eos_designs_to_containerlab/blob/main/action_plugins/simulation.py#L250 outside of the wider if block in https://github.com/arista-netdevops-community/eos_designs_to_containerlab/blob/main/action_plugins/simulation.py#L242. If this code could be moved, our mappings json files then come out correctly as follows:

```
{
    "EthernetIntf": {
        "eth1": "Ethernet1/1",
        "eth10": "Ethernet10/1",
        "eth11": "Ethernet11/1",
        "eth12": "Ethernet12/1",
        "eth13": "Ethernet13/1",
        "eth14": "Ethernet14/1",
        "eth15": "Ethernet15/1",
        "eth16": "Ethernet16/1",
        "eth17": "Ethernet17/1",
        "eth18": "Ethernet18/1",
        "eth19": "Ethernet19/1",
        "eth2": "Ethernet2/1",
        "eth20": "Ethernet20/1",
        "eth21": "Ethernet21/1",
        "eth22": "Ethernet22/1",
        "eth23": "Ethernet23/1",
        "eth24": "Ethernet24/1",
        "eth25": "Ethernet25/1",
        "eth26": "Ethernet26/1",
        "eth27": "Ethernet27/1",
        "eth28": "Ethernet28/1",
        "eth29": "Ethernet29/1",
        "eth3": "Ethernet3/1",
        "eth30": "Ethernet30/1",
        "eth31": "Ethernet31/1",
        "eth32": "Ethernet32/1",
        "eth33": "Ethernet33/1",
        "eth34": "Ethernet34/1",
        "eth35": "Ethernet35/1",
        "eth36": "Ethernet36/1",
        "eth4": "Ethernet4/1",
        "eth5": "Ethernet5/1",
        "eth6": "Ethernet6/1",
        "eth7": "Ethernet7/1",
        "eth8": "Ethernet8/1",
        "eth9": "Ethernet9/1"
    },
    "ManagementIntf": {
        "eth0": "Management1"
    }
}
```

**Comment by bjmeuer** [comment]
Hi Andrew, 

this was done on purpose to only configure an interface if there is a peer_interface defined. Are you using the "network_ports" from eos_designs? If so this is not supported for now, but can have a look if it is possible to make it useable. 

How would you image to define the connection in the containerlab topology file if I don't have any peer_interface?

With peer_interface defined the following connection line can be specified as an example:
`- endpoints: ["DC2-LEAF-01B:eth3", "Server:eth4"]`

Without peer_interface would you like something like this (using the clab dummy interface feature https://containerlab.dev/manual/topo-def-file/#dummy):
`- endpoints: ["DC2-LEAF-01B:eth3", "Server:dummyX"]`

Thanks,
Bjoern

**Comment by andrewbonney** [comment]
Hi Bjoern,
We're using `eos_cli_config_gen` directly, but I'm surprised if this is an issue directly because of the way we're using it. We use `peer_interface` to define connections as well, but if you don't have every switch port connected/configured, and have a gap in the middle (i.e. Eth1/1 is in use, Eth2/1 isn't, then Eth3/1 is used), then the startup-config will reference Eth1/1 and Eth3/1, but the containerlab switch will only have Eth1/1 and Eth2/1, which means Eth2/1 has no config because it was expected to be named Eth3/1.

In case it's any clearer, here's a diff for what is working for us:

```
diff --git a/action_plugins/simulation.py b/action_plugins/simulation.py
index 6bb6b96..63c6874 100644
--- a/action_plugins/simulation.py
+++ b/action_plugins/simulation.py
@@ -246,12 +246,6 @@ class ActionModule(ActionBase):
                             if "is_deployed" in hostvars[eth["peer"]] and hostvars[eth["peer"]]["is_deployed"] == False:
                                 continue
                         
-                        # create EOS interface to linux eth mapping if needed
-                        if containerlab_custom_interface_mapping:
-                            tmp_intf_mapping = {str((eth["name"].split("."))[0]):"eth"+str(intf_counter)}
-                            switch_intf_mapping_dict[switch].update(tmp_intf_mapping)
-                            intf_counter += 1
-
                         # if sim_env is 'clab' replace 'Ethernet' with 'eth' and '/' with '_'      
                         if sim_env == "clab" and not containerlab_custom_interface_mapping:
                             loc_int = str((eth["name"].split("."))[0]).replace("Ethernet","eth").replace("/","_")
@@ -298,6 +292,12 @@ class ActionModule(ActionBase):
                                     elif not sim_external_node_one_container:
                                         ext_nodes.append({eth["peer"]:node_type})
 
+                    # create EOS interface to linux eth mapping if needed
+                    if containerlab_custom_interface_mapping:
+                        tmp_intf_mapping = {str((eth["name"].split("."))[0]):"eth"+str(intf_counter)}
+                        switch_intf_mapping_dict[switch].update(tmp_intf_mapping)
+                        intf_counter += 1
+
         # Additional containerlab mgmt connection defined in vars of SIMULATION Host                         
         for element in containerlab_add_mgmt_links:
             tmp_conn = {"loc_switch":element["node"], "loc_int":element["intf"], "peer_name":"mgmt-net", "peer_int":element["node"]+"-"+element["intf"]}
```

**Comment by bjmeuer** [comment]
> Hi Bjoern, We're using `eos_cli_config_gen` directly, but I'm surprised if this is an issue directly because of the way we're using it. We use `peer_interface` to define connections as well, but if you don't have every switch port connected/configured, and have a gap in the middle (i.e. Eth1/1 is in use, Eth2/1 isn't, then Eth3/1 is used), then the startup-config will reference Eth1/1 and Eth3/1, but the containerlab switch will only have Eth1/1 and Eth2/1, which means Eth2/1 has no config because it was expected to be named Eth3/1.
> 
> In case it's any clearer, here's a diff for what is working for us:
> 
> ```
> diff --git a/action_plugins/simulation.py b/action_plugins/simulation.py
> index 6bb6b96..63c6874 100644
> --- a/action_plugins/simulation.py
> +++ b/action_plugins/simulation.py
> @@ -246,12 +246,6 @@ class ActionModule(ActionBase):
>                              if "is_deployed" in hostvars[eth["peer"]] and hostvars[eth["peer"]]["is_deployed"] == False:
>                                  continue
>                          
> -                        # create EOS interface to linux eth mapping if needed
> -                        if containerlab_custom_interface_mapping:
> -                            tmp_intf_mapping = {str((eth["name"].split("."))[0]):"eth"+str(intf_counter)}
> -                            switch_intf_mapping_dict[switch].update(tmp_intf_mapping)
> -                            intf_counter += 1
> -
>                          # if sim_env is 'clab' replace 'Ethernet' with 'eth' and '/' with '_'      
>                          if sim_env == "clab" and not containerlab_custom_interface_mapping:
>                              loc_int = str((eth["name"].split("."))[0]).replace("Ethernet","eth").replace("/","_")
> @@ -298,6 +292,12 @@ class ActionModule(ActionBase):
>                                      elif not sim_external_node_one_container:
>                                          ext_nodes.append({eth["peer"]:node_type})
>  
> +                    # create EOS interface to linux eth mapping if needed
> +                    if containerlab_custom_interface_mapping:
> +                        tmp_intf_mapping = {str((eth["name"].split("."))[0]):"eth"+str(intf_counter)}
> +                        switch_intf_mapping_dict[switch].update(tmp_intf_mapping)
> +                        intf_counter += 1
> +
>          # Additional containerlab mgmt connection defined in vars of SIMULATION Host                         
>          for element in containerlab_add_mgmt_links:
>              tmp_conn = {"loc_switch":element["node"], "loc_int":element["intf"], "peer_name":"mgmt-net", "peer_int":element["node"]+"-"+element["intf"]}
> ```

it should not happen that you run into an issue, even if you have gabs in between the defined interfaces. Taking your example it should render the EosIntfMapping.json file like this:

```
{
    "EthernetIntf": {
        "eth1": "Ethernet1/1",
        "eth2": "Ethernet3/1"
    },
    "ManagementIntf": {
        "eth0": "Management1"
    }
}
```

and in the containerlab topology it should look like:

```
- endpoints: ["DC2-LEAF-01A:eth1", "DC2-LEAF-01B:eth1"]
- endpoints: ["DC2-LEAF-01A:eth2", "DC2-LEAF-01B:eth2"]
```

this is only if the peer and peer_interface are defined correctly. For example:

```
ethernet_interfaces:
  - name: Ethernet1/1
    description: to_DC2-LEAF-01B
    ...
    peer: DC2-LEAF-01B
    peer_interface: Ethernet1/1
    ...
```

Maybe I'm missing something here. Could you provide the relevant parts from the .yml files, so I can test it?

Thanks

**Comment by bjmeuer** [comment]
> Apologies, I'm now unable to replicate the issue. I agree and was seeing what you describe, but the containerlab switch always ended up with sequential interfaces (ie. `Ethernet1/1` and `Ethernet2/1` in this case (rather than 3/1)). This no longer seems to happen so I assume I had made a config error previously.

No worries, thanks for double checking.

Let me know if it happens again in future.
