### ISSUE TITLE
Action plugin attempts to remove directory which may not exist

### ISSUE THREAD

**Issue by andrewbonney** [arista-netdevops-community/eos_designs_to_containerlab#9]
On line 495, a directory ending `_mappings` is created subject to the value of a variable: https://github.com/arista-netdevops-community/eos_designs_to_containerlab/blob/dev/action_plugins/simulation.py#L495

On line 535, this directory is cleaned up, whether the variable is set of not: https://github.com/arista-netdevops-community/eos_designs_to_containerlab/blob/dev/action_plugins/simulation.py#L535

If the variable is unset, this results in a FileNotFoundError exception. Could this cleanup either be surround with an exception handler, or take account of the variable used in its creation?

**Comment by bjmeuer** [comment]
thanks for bringing up that issue. this should be fixed with PR #12
